name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Approve Cypress build script
        run: pnpm exec pnpm-approve-builds cypress
      - name: Install Cypress binary
        run: npx cypress install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome